import './style.css'
// import './ejercicios/introduccion/ejercicio2'
// import './ejercicios/introduccion/ejercicio3'
// import './ejercicios/2operadoresLogYCond/ejercicio1'
// import './ejercicios/2operadoresLogYCond/ejercicio2'
// import './ejercicios/3opAsignYBucles/ejercicio1'
// import './ejercicios/3opAsignYBucles/ejercicio2'
// import './ejercicios/4funciones/ejercicio1'
// import './ejercicios/4funciones/ejercicio2'
// import './ejercicios/5objetos/ejercicio1'
// import './ejercicios/5objetos/ejercicio2'
// import './ejercicios/6arrays/ejercicio1'
// import './ejercicios/6arrays/ejercicio2'
// import './ejercicios/7introDom/ejercicio1'
// import './ejercicios/7introDom/ejercicio2'
// import './ejercicios/8eventosDom/ejercicio1'
import './ejercicios/8eventosDom/ejercicio2'

